name: "Podcast by Mahadevan"
author: "Mahadevan"
description: "A podcast about the world of technology, business, and life."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "podcast"
  color: "blue"
inputs:
  email:
    description: "Email address to send the podcast link."
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "Name of the person to send the podcast link."
    required: true
    default: ${{ github.actor }}
